// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyUAJ7zWKAz7ZTJruSrSal0KN5NKXrtxU',
    appId: '1:786578883955:web:4f1000f0dfa5298227b106',
    messagingSenderId: '786578883955',
    projectId: 'chems21-3dbe3',
    authDomain: 'chems21-3dbe3.firebaseapp.com',
    databaseURL: 'https://chems21-3dbe3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chems21-3dbe3.firebasestorage.app',
    measurementId: 'G-K5HVDJ00BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM9RQX1qM9Vdrw0BanWjvKGgdvFrYpQa8',
    appId: '1:786578883955:android:470ee4025e1b1fbc27b106',
    messagingSenderId: '786578883955',
    projectId: 'chems21-3dbe3',
    databaseURL: 'https://chems21-3dbe3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chems21-3dbe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQu_rp21_mcWVJg4_IDw550GKFUQmxZI',
    appId: '1:786578883955:ios:544c09687bf76d6027b106',
    messagingSenderId: '786578883955',
    projectId: 'chems21-3dbe3',
    databaseURL: 'https://chems21-3dbe3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chems21-3dbe3.firebasestorage.app',
    iosBundleId: 'com.example.nexdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQu_rp21_mcWVJg4_IDw550GKFUQmxZI',
    appId: '1:786578883955:ios:544c09687bf76d6027b106',
    messagingSenderId: '786578883955',
    projectId: 'chems21-3dbe3',
    databaseURL: 'https://chems21-3dbe3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chems21-3dbe3.firebasestorage.app',
    iosBundleId: 'com.example.nexdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyUAJ7zWKAz7ZTJruSrSal0KN5NKXrtxU',
    appId: '1:786578883955:web:798e21794681878227b106',
    messagingSenderId: '786578883955',
    projectId: 'chems21-3dbe3',
    authDomain: 'chems21-3dbe3.firebaseapp.com',
    databaseURL: 'https://chems21-3dbe3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chems21-3dbe3.firebasestorage.app',
    measurementId: 'G-Z3BX7RDRFQ',
  );

}